### ISSUE TITLE
PreferenceEditForm Undefined index: confcat_id

### ISSUE THREAD

**Issue by gigamaster** [xoopscube/xcl#63] opened 2019-04-13 03:26 UTC
NOTICE: Undefined index: confcat_id

public function __construct($category)
    {
        // ! call parent::__construct() instead of parent::Controller()
        parent::__construct();
        //parent::XCube_ActionForm();
       // Add if isset
        if (isset($mKeyName['confcat_id'])) {
            $this->mKeyValue = $category->get('confcat_id');
        }
    }

**Comment by gigamaster** [comment] 2019-04-18 12:57
Did not fix NOTICE: Undefined index: confcat_id - I mixed with conf_catid !!!

**Comment by nunoluciano** [comment] 2020-05-10 08:07
The issue comes from the template `preference_list.html` and wont fix by design.
because the two links to preferences of modules **user** and **render**
preferences were added without root redirection.

**Closed** 2020-05-14 20:39 UTC
Labels: bug
